server:
  port: 8041

spring:
  profiles:
    active: native

  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
